### ISSUE TITLE
Improve the Docs

### ISSUE THREAD

**Issue by digaoddc** [lucafaggianelli/mario-pype#97]
Hello,

I was trying to run the project using the readme, and I got some problems.

The `authlib` is a project dependency(https://github.com/lucafaggianelli/mario-pype/blob/0d35c44b4c74dfd225b1749f45cab865b2adb3b6/mario/api/authentication.py#L1), but is not listed in the dependencies file, so I had do install manually.  I think it should be included as a dependency.

The lib `itsdangerous` was required by the `starlette` dependency:

```
File "/root/.cache/pypoetry/virtualenvs/api-9TtSrW0h-py3.11/lib/python3.11/site-packages/mario/api/authentication.py", line 4, in <module>                                                                       
    from starlette.middleware.sessions import SessionMiddleware                                                                                                                                                    
  File "/root/.cache/pypoetry/virtualenvs/api-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 6, in <module>                                                                  
    import itsdangerous                                                                                                                                                                                            
ModuleNotFoundError: No module named 'itsdangerous'                                   
```
And finally, I'm not still able to run the project because I got this error `URL host invalid, top level domain required (type=value_error.url.host)`. 

What about adding the supported and required configurations in the README? It will help a lot.

Thank you.

**Comment by lucafaggianelli** [comment]
Hi,

sorry for that and thanks for notifying about this issue

I'll add the missing dependencies!

About the URL error, it's a bug and I'm correcting it.

Yeah documentation is pretty limited at the moment, I'm creating a doc website though. I'll add some info about the configuration in the README in the meanwhile!
